name: Pull Request

on:
  pull-request:
    branches: master

jobs:
  test-pr:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: ['12x', '14x', '16x']
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - name: Configure Git
      uses: actions/checkout@v2
    
    - name: Configure Node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: npm ci

    - name: Build Project
      run: npm run build

    - name: Run Test
      run: npm run test